# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: runner1

    steps:
#    - uses: actions/checkout@v1
    - name: git pull odman
      run: |
        pwd
        if [ ! -d "/home/ec2-user/actions-runner/_work/odman/odman" ]; then
        git clone https://github.com/sunyaxiong/odman.git; else cd /home/ec2-user/actions-runner/_work/odman&&git pull; fi
#    - name: Set up Python 3.8
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.8
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install flake8 pytest
#        if [ -f ./odman/requirements.txt ]; then pip install -r ./odman/requirements.txt; fi
    - name: Test with pytest
      run: |
        echo "Hello World"
